# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            jylt
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jon Tan'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/poole/hyde


plugins:
  - jekyll-paginate
  - jekyll-gist