# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            jylt
# tagline:          'A Jekyll theme'
description:      Writings
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jon Tan'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/poole/hyde


plugins:
  - jekyll-paginate
  - jekyll-gist